### ISSUE TITLE
(v4) Database sharding using TimescaleDB

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-db#68]
In order to shard our database with TimescaleDB e need to:

- [x] Denormalize tables by `block_number`, so that we can partition tables by block range: https://github.com/vulcanize/ipld-eth-db/pull/51
- [x] Adjust all unique constraints (e.g. primary keys) to include the partition key (block_number)
- [x] Migrations for hypertables and distributed hypertables
- [x] Script for adding new data nodes to the distributed hypertables
- [x] Stored procedures for state and storage snapshot generation
- [x] Figure out how to handle foreign keys (apply directly to data nodes? fork timescaleDB?): https://github.com/vulcanize/ipld-eth-db/issues/69

**Comment by prathamesh0** [comment]
- Currently, we are working with a single node setup (hypertables) because of multiple issues with multi-node setup (see [comment](https://github.com/vulcanize/issue_tracking/issues/16)).
- The multi-node changes are on branch [sharding-multi-node](https://github.com/vulcanize/ipld-eth-db/tree/sharding-multi-node) and have been put on hold for now.
- The `ipld-eth-db` image is configured to run migrations directly.
- Deployment:
  - Currently using docker setup.
  - Minikube/k8s setup https://github.com/timescale/timescaledb-kubernetes/issues/363

**Comment by prathamesh0** [comment]
Additional tasks:

- [ ]  Update the workflow to test up-down migrations
- [ ]  Update script to generate migration for adding data nodes (multi-node)

**Comment by i-norden** [comment]
Closing this, will open an issue for the remaining low-priority tasks.
